// 📁 src/features/admin/api/tourRequestsApi.js

import apiClient from "../../../services/apiClient";

export const MOCK_MODE = true;

export const MOCK_TOURS = [
  {
    id:            "tr_7999",
    createdAt:     "Jan 29, 2026 3:50 PM",
    source:        "app",
    property:      { name: "Modern 2BR Apartment",  location: "Woodlands, Lusaka" },
    customer:      { name: "Ravi K.",    phone: "+260971111111" },
    visitType:     "virtual",
    preferredSlot: "Jan 30, 2026 5:30 PM",
    finalSlot:     null,
    agent:         null,
    status:        "Requested",
    sla:           "Overdue",
  },
  {
    id:            "tr_7001",
    createdAt:     "Jan 28, 2026 2:00 PM",
    source:        "app",
    property:      { name: "3BR Family Home",        location: "Kabulonga, Lusaka" },
    customer:      { name: "Martha Z.", phone: "+260972222222" },
    visitType:     "physical",
    preferredSlot: "Jan 30, 2026 3:30 PM",
    finalSlot:     "Jan 30, 2026 3:30 PM",
    agent:         "Agent Alice",
    status:        "Proposed",
    sla:           "Overdue",
  },
  {
    id:            "tr_7003",
    createdAt:     "Jan 27, 2026 7:30 PM",
    source:        "app",
    property:      { name: "Office Space – CBD",     location: "Lusaka CBD" },
    customer:      { name: "Kunda M.",  phone: "+260973333333" },
    visitType:     "physical",
    preferredSlot: "Jan 29, 2026 2:30 PM",
    finalSlot:     "Jan 29, 2026 4:30 PM",
    agent:         "Agent Chipo",
    status:        "Confirmed",
    sla:           null,
  },
  {
    id:            "tr_7010",
    createdAt:     "Jan 28, 2026 11:30 AM",
    source:        "website",
    property:      { name: "Modern 2BR Apartment",   location: "Woodlands, Lusaka" },
    customer:      { name: "Brian L.",  phone: "+260974444444" },
    visitType:     "virtual",
    preferredSlot: "Jan 30, 2026 2:30 PM",
    finalSlot:     null,
    agent:         null,
    status:        "Requested",
    sla:           "Overdue",
  },
  {
    id:            "tr_7004",
    createdAt:     "Jan 26, 2026 4:30 PM",
    source:        "call",
    property:      { name: "Luxury Penthouse",       location: "Roma, Lusaka" },
    customer:      { name: "Susan N.",  phone: "+260975555555" },
    visitType:     "physical",
    preferredSlot: "Jan 31, 2026 7:30 PM",
    finalSlot:     "Jan 31, 2026 7:30 PM",
    agent:         "Agent Bob",
    status:        "Confirmed",
    sla:           null,
  },
  {
    id:            "tr_7005",
    createdAt:     "Jan 25, 2026 10:00 AM",
    source:        "website",
    property:      { name: "4BR Garden Villa",       location: "Kabulonga, Lusaka" },
    customer:      { name: "James M.",  phone: "+260976666666" },
    visitType:     "physical",
    preferredSlot: "Jan 28, 2026 11:00 AM",
    finalSlot:     "Jan 28, 2026 11:00 AM",
    agent:         "Agent Alice",
    status:        "Completed",
    sla:           null,
  },
  {
    id:            "tr_7006",
    createdAt:     "Jan 24, 2026 9:00 AM",
    source:        "app",
    property:      { name: "Studio Apartment CBD",   location: "Lusaka CBD" },
    customer:      { name: "Mercy K.",  phone: "+260977777777" },
    visitType:     "virtual",
    preferredSlot: "Jan 26, 2026 3:00 PM",
    finalSlot:     null,
    agent:         null,
    status:        "Requested",
    sla:           "Overdue",
  },
  {
    id:            "tr_7007",
    createdAt:     "Jan 23, 2026 2:00 PM",
    source:        "call",
    property:      { name: "3BR Townhouse",          location: "Woodlands, Lusaka" },
    customer:      { name: "Peter N.",  phone: "+260978888888" },
    visitType:     "physical",
    preferredSlot: "Jan 25, 2026 10:00 AM",
    finalSlot:     "Jan 25, 2026 10:00 AM",
    agent:         "Agent Chipo",
    status:        "Proposed",
    sla:           "Overdue",
  },
  {
    id:            "tr_7008",
    createdAt:     "Jan 22, 2026 11:00 AM",
    source:        "website",
    property:      { name: "Commercial Space",       location: "Lusaka CBD" },
    customer:      { name: "Anna W.",   phone: "+260979999999" },
    visitType:     "virtual",
    preferredSlot: "Jan 24, 2026 2:00 PM",
    finalSlot:     "Jan 24, 2026 2:00 PM",
    agent:         "Agent Bob",
    status:        "Completed",
    sla:           null,
  },
];

export const fetchTourRequests = async (params = {}) => {
  const { data } = await apiClient.get("/tour-requests", { params });
  return data;
};